load("Results/Argentina.RData")
load("Results/Brazil.RData")
load("Results/Chile.RData")
load("Results/Colombia.RData")
load("Results/CostaRica.RData")
load("Results/Ecuador.RData")
load("Results/Mexico.RData")
load("Results/Uruguay.RData")
load("Results/Venezuela.RData")
rm(list=setdiff(ls(), c("ARGSpec",
"ARGMS",
"ARGPhD",
"BRASpec",
"BRAMS",
"BRAPhD",
"CHLSpec",
"CHLMS",
"CHLPhD",
"COLSpec",
"COLMS",
"COLPhD",
"CORISpec",
"CORIMS",
"CORIPhD",
"ECUSpec",
"ECUMS",
"ECUPhD",
"MEXSpec",
"MEXMS",
"MEXPhD",
"URUSpec",
"URUMS",
"URUPhD",
"VENSpec",
"VENMS",
"VENPhD")))
