load("MEX.RData")
load("CHL.RData")
load("COL.RData")
load("VEN.RData")
load("ECU.RData")
rm(list=setdiff(ls(), c("ProgramsMX","ProgramsCL", "ProgramsCO", "ProgramsVE", "ProgramsEC")))
ProgramsCL$Country <- "Chile"
ProgramsCL$Skill <- rownames(ProgramsCL)
ProgramsCO$Country <- "Colombia"
ProgramsCO$Skill <- rownames(ProgramsCO)
ProgramsEC$Country <- "Ecuador"
ProgramsEC$Skill <- rownames(ProgramsEC)
ProgramsVE$Country <- "Venezuela"
ProgramsVE$Skill <- rownames(ProgramsVE)
ProgramsMX$Country <- "Mexico"
ProgramsMX$Skill <- rownames(ProgramsMX)
df <- mget(ls(pattern = "Programs"))
SS <- do.call(rbind, df)

SS$Skill <- ifelse(SS$Skill == "s1","pensamiento crítico", NA)
SS$Skill <- ifelse(SS$Skill == "s2","solucionar problemas", NA)
SS$Skill <- ifelse(SS$Skill == "s3","comunicar", NA)
SS$Skill <- ifelse(SS$Skill == "s4","creatividad", NA)
SS$Skill <- ifelse(SS$Skill == "s5","paciencia", NA)
SS$Skill <- ifelse(SS$Skill == "s6","crear", NA)
SS$Skill <- ifelse(SS$Skill == "s7","liderar", NA)
SS$Skill <- ifelse(SS$Skill == "s8","resolver", NA)
SS$Skill <- ifelse(SS$Skill == "s9","comprometer", NA)
SS$Skill <- ifelse(SS$Skill == "s10","comprometerse", NA)
SS$Skill <- ifelse(SS$Skill == "s11","gestionar", NA)
SS$Skill <- ifelse(SS$Skill == "s12","reflexionar", NA)
SS$Skill <- ifelse(SS$Skill == "s13","controlar", NA)
SS$Skill <- ifelse(SS$Skill == "s14","ético", NA)
SS$Skill <- ifelse(SS$Skill == "s15","tolerar", NA)
SS$Skill <- ifelse(SS$Skill == "s16","argumentar", NA)
SS$Skill <- ifelse(SS$Skill == "s17","conflictos", NA)
SS$Skill <- ifelse(SS$Skill == "s18","negociar", NA)
SS$Skill <- ifelse(SS$Skill == "s19","comprender", NA)
SS$Skill <- ifelse(SS$Skill == "s20","", NA)
SS$Skill <- ifelse(SS$Skill == "s21","", NA)
SS$Skill <- ifelse(SS$Skill == "s22","", NA)
SS$Skill <- ifelse(SS$Skill == "s23","", NA)
SS$Skill <- ifelse(SS$Skill == "s24","", NA)
SS$Skill <- ifelse(SS$Skill == "s25","", NA)
SS$Skill <- ifelse(SS$Skill == "s26","", NA)
SS$Skill <- ifelse(SS$Skill == "s27","", NA)
SS$Skill <- ifelse(SS$Skill == "s28","", NA)
SS$Skill <- ifelse(SS$Skill == "s29","", NA)
SS$Skill <- ifelse(SS$Skill == "s30","", NA)
SS$Skill <- ifelse(SS$Skill == "s31","", NA)
SS$Skill <- ifelse(SS$Skill == "s32","", NA)
SS$Skill <- ifelse(SS$Skill == "s33","", NA)
SS$Skill <- ifelse(SS$Skill == "s34","", NA)
SS$Skill <- ifelse(SS$Skill == "s35","", NA)
SS$Skill <- ifelse(SS$Skill == "s36","", NA)
SS$Skill <- ifelse(SS$Skill == "s37","", NA)
SS$Skill <- ifelse(SS$Skill == "s38","", NA)
SS$Skill <- ifelse(SS$Skill == "s39","", NA)
SS$Skill <- ifelse(SS$Skill == "s40","", NA)
SS$Skill <- ifelse(SS$Skill == "s41","", NA)
SS$Skill <- ifelse(SS$Skill == "s42","", NA)
SS$Skill <- ifelse(SS$Skill == "s43","", NA)
SS$Skill <- ifelse(SS$Skill == "s44","", NA)
SS$Skill <- ifelse(SS$Skill == "s45","", NA)
SS$Skill <- ifelse(SS$Skill == "s46","", NA)
SS$Skill <- ifelse(SS$Skill == "s47","", NA)
SS$Skill <- ifelse(SS$Skill == "s48","", NA)
SS$Skill <- ifelse(SS$Skill == "s49","", NA)
SS$Skill <- ifelse(SS$Skill == "s50","", NA)

