---
title: "Supplemental Material Basic Skills Academic Offering"
author: "Juan C. Correa"
date: "2024-12-14"
output: html_document
---

```{r, echo = FALSE, warning = FALSE}
# Packages
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(network))
suppressPackageStartupMessages(library(igraph))
```


# 1 Data loading
```{r}
load("Results/Argentina.RData")
load("Results/Brazil.RData")
load("Results/Chile.RData")
load("Results/Colombia.RData")
load("Results/CostaRica.RData")
load("Results/Ecuador.RData")
load("Results/Mexico.RData")
load("Results/Uruguay.RData")
load("Results/Venezuela.RData")

```

# 2. Network general characteristics of skills-programs academic offering by country

```{r}
Argentina
Brazil
Chile
Colombia
CostaRica
```



# 3. Eigenvector centrality degree distributions for skills and programs
```{r}
AllCountries <- do.call(rbind, list(ProgramsARG,
                                   ProgramsBRA,
                                   ProgramsCHL,
                                   ProgramsCOL,
                                   ProgramsCORI,
                                   ProgramsECU,
                                   ProgramsMEX,
                                   ProgramsURU,
                                   ProgramsVEN))

AllCountries %>%
  group_by(Partition,Country) %>%
  summarize(
    N = length(Node),
    Mean = mean(Eigenvector),
    SD = sd(Eigenvector)
  )

AllPrograms <- do.call(rbind, list(ProgramsARG1,
                                   ProgramsARG2,
                                   ProgramsARG3,
                                   ProgramsBRA1,
                                   ProgramsBRA2,
                                   ProgramsBRA3,
                                   ProgramsCHL1,
                                   ProgramsCHL2,
                                   ProgramsCHL3,
                                   ProgramsCOL1,
                                   ProgramsCOL2,
                                   ProgramsCOL3,
                                   ProgramsCORI1,
                                   ProgramsCORI2,
                                   ProgramsCORI3,
                                   ProgramsECU1,
                                   ProgramsECU2,
                                   ProgramsECU3,
                                   ProgramsMEX1,
                                   ProgramsMEX2,
                                   ProgramsMEX3,
                                   ProgramsURU1,
                                   ProgramsURU2,
                                   ProgramsURU3,
                                   ProgramsVEN1,
                                   ProgramsVEN2,
                                   ProgramsVEN3))
```



```{r, message = FALSE, warning = FALSE}
ggplot(AllPrograms, aes(x=Level, y=Eigenvector, fill = Partition)) +
  geom_boxplot(notch = TRUE) +
  scale_x_discrete(limits = c("Specialization", "Master", "PhD")) +
  facet_wrap(~Country) +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black")) +
  xlab("") + ylab("Eigenvector centrality degree") +
  scale_fill_manual(values = c("Skill" = "#09419e", "Program" = "#FFFFFF"))
```

